Description: AWS CloudFormation Template to create AWS Secret, KMS key and relevant IAM policies
Parameters:
  ProjectName:
    Description: Project Name (This will be associated with Tags)
    Type: String
    Default: Upwork
  SecretNameSpace:
    Description: Namespace for Secret
    Type: String
    Default: /prod/databases/dbserver1
  AccessPolicy:
    Description: Access policy to Secret
    Type: String
    AllowedValues:
     - ReadOnly
     - WriteOnly
     - ReadAndWrite
    Default: ReadOnly
  UsersList:
    Description: Current USer ARN to give access to KMS key
    Type: String
    Default: arn:aws:iam::713807340749:root

Conditions:
  ReadOnly: !Equals [ !Ref AccessPolicy, ReadOnly ]
  WriteOnly: !Equals [ !Ref AccessPolicy, WriteOnly ]
  ReadAndWrite: !Equals [ !Ref AccessPolicy, eadAndWrite ]

Resources:
  SecretManager:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: AWS Secret Manager
      GenerateSecretString:
        SecretStringTemplate: '{"Purpose": "Random Password"}'
        GenerateStringKey: password
        PasswordLength: 15
      KmsKeyId: !Ref KMSKey
      Name: !Ref SecretNameSpace
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Secret'

  ReadOnlyPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Condition: ReadOnly
    Properties:
      Description: !Sub  Policy for read only access to Secret Manager in project ${ProjectName}
      ManagedPolicyName: !Sub '${ProjectName}-ReadOnlyPolicy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
             - "secretsmanager:GetSecretValue"
             - "secretsmanager:DescribeSecret"
             - "secretsmanager:ListSecretVersionIds"
             - "secretsmanager:GetResourcePolicy"
             - 'kms:DescribeKey'
             - 'kms:Encrypt'
             - 'kms:Decrypt'
             - 'kms:ReEncrypt*'
             - 'kms:GenerateDataKey'
             - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: 
             - !Ref SecretManager
             - !GetAtt KMSKey.Arn
          - Effect: Allow
            Action:
             - "secretsmanager:ListSecrets"
            Resource: "*"
      Users: !Split [",", !Ref UsersList]

  WriteOnlyPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Condition: WriteOnly
    Properties:
      Description: !Sub  Policy for write only access to Secret Manager in project ${ProjectName}
      ManagedPolicyName: !Sub '${ProjectName}-WriteOnlyPolicy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
             - "secretsmanager:GetSecretValue"
             - "secretsmanager:DescribeSecret"
             - "secretsmanager:ListSecretVersionIds"
             - "secretsmanager:GetResourcePolicy"            
             - "secretsmanager:PutSecretValue"
             - "secretsmanager:CancelRotateSecret"
             - "secretsmanager:CreateSecret"
             - "secretsmanager:DeleteSecret"
             - "secretsmanager:PutSecretValue"
             - "secretsmanager:RestoreSecret"
             - "secretsmanager:RotateSecret"
             - "secretsmanager:UpdateSecret"
             - "secretsmanager:UpdateSecretVersionStage"
             - 'kms:DescribeKey'
             - 'kms:Encrypt'
             - 'kms:Decrypt'
             - 'kms:ReEncrypt*'
             - 'kms:GenerateDataKey'
             - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: 
             - !Ref SecretManager
             - !GetAtt KMSKey.Arn
          - Effect: Allow
            Action:
             - "secretsmanager:ListSecrets"
            Resource: "*"
      Users: !Split [",", !Ref UsersList]

  ReadAndWritePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Condition: ReadAndWrite
    Properties:
      Description: !Sub  Policy for read and write access to Secret Manager in project ${ProjectName}
      ManagedPolicyName: !Sub '${ProjectName}-ReadAndWritePolicy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
             - "secretsmanager:GetSecretValue"
             - "secretsmanager:DescribeSecret"
             - "secretsmanager:ListSecretVersionIds"
             - "secretsmanager:GetResourcePolicy"            
             - "secretsmanager:PutSecretValue"
             - "secretsmanager:CancelRotateSecret"
             - "secretsmanager:CreateSecret"
             - "secretsmanager:DeleteSecret"
             - "secretsmanager:PutSecretValue"
             - "secretsmanager:RestoreSecret"
             - "secretsmanager:RotateSecret"
             - "secretsmanager:UpdateSecret"
             - "secretsmanager:UpdateSecretVersionStage"
             - 'kms:DescribeKey'
             - 'kms:Encrypt'
             - 'kms:Decrypt'
             - 'kms:ReEncrypt*'
             - 'kms:GenerateDataKey'
             - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: 
             - !Ref SecretManager
             - !GetAtt KMSKey.Arn
          - Effect: Allow
            Action:
             - "secretsmanager:ListSecrets"
            Resource: "*"
      Users: !Split [",", !Ref UsersList]

  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: An symmetric CMK for Secret Manager
      EnableKeyRotation: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-KMS-Key'
